### ISSUE TITLE
installer fails if user-repos < config repos

### ISSUE THREAD

**Issue by finki70** [shaansubbaiah/Portfolio#10]
I got that error when inserting 200 as repo number
`Starting Build
✔️ Fetched data from Github
✔️ Copied files
⚠️ Failed!
Error: Cannot read property 'name' of null`

**Comment by shaansubbaiah** [comment]
Max number of repos is 99, for more than 99 we need to use pagination with the GitHub graphql API and I don't think anyone will display more than 100 repositories at once.
