### ISSUE TITLE
Fix overflow

### ISSUE THREAD

**Issue by finki70** [shaansubbaiah/Portfolio#13]
![Screenshot_20201002-080547_Chrome](https://user-images.githubusercontent.com/38655889/94892870-25b9e280-0486-11eb-9dbf-f15733e8f7e1.jpg)

**Comment by shaansubbaiah** [comment]
What was the device resolution?

**Comment by tusharmaharana** [comment]
Hey I figured out this issue, the words were not breaking to the next line. I'm working to send the PR now
