### ISSUE TITLE
extend readme

### ISSUE THREAD

**Issue by finki70** [shaansubbaiah/Portfolio#14]
you wrote, that users have to insert the twitter id, but the usernamen should work as well.

**Comment by finki70** [comment]
Well, I also mean, that you add an information Like "Twitter id or username", I thought I had to get my Twitter id, and Not my username

**Comment by shaansubbaiah** [comment]
Haha, I have barely used Twitter, I'm sure of the difference between the Twiiter username and ID. I meant the Twitter handle because the link is created by appending to `https://twitter.com/`. Let me know if there are changes to be made, I'll edit the previous commit.

**Comment by finki70** [comment]
As you see at following url, it should work :) 
https://twitter.com/xndrxxs_fxnk
