### ISSUE TITLE
Serve JS & fonts local

### ISSUE THREAD

**Issue by AFink** [shaansubbaiah/Portfolio#23]
For privacy reasons, the js & font files could be downloaded with npm and packed with [webpack](https://webpack.js.org/)?
This could be also a nice first issue.

**Comment by shaansubbaiah** [comment]
I think only `masonry js` is from an external source. The fonts (Poppins) are from Google so they load faster when served online as they're cached generally.

**Comment by finki70** [comment]
Yearh, in germany, we have a GDPR and some people like me are afraid to break it, so I include in every of my projetcts local fonts & local js/css

**Comment by shaansubbaiah** [comment]
Served locally now that I'm using Vite to build the app.
