### ISSUE TITLE
Download avatar

### ISSUE THREAD

**Issue by finki70** [shaansubbaiah/Portfolio#24]
As I said in #23 , I would like to serve everything locally, so we could download the avatar in `build.js` (variable `dt.user.avatarUrl`) and store it into `/dist/assets/png/avatar.png`. Then we dont need build.js line 86-96 anymore.

Also a nice first issue, but I can also work on it by myself.

**Comment by shaansubbaiah** [comment]
Yeah this can be done, makes more sense than loading the Google font locally. I guess then a user should also be able to select a local picture while setting up the config.

**Comment by shaansubbaiah** [comment]
I'll mark this open for Hacktober

**Comment by shaansubbaiah** [comment]
Fix in progress in #29
