### ISSUE TITLE
Repo cards overlap on first load

### ISSUE THREAD

**Issue by shaansubbaiah** [shaansubbaiah/Portfolio#7]
Fixed by a refresh/ resizing the browser window.

I had attempted a fix by trying various ways to reload once after the document has loaded to no success.
Another way to fix would be to remove masonry-js from the repository cards section and use flex with animations instead.

![untitled](https://user-images.githubusercontent.com/11163839/94772426-39f2d680-03d7-11eb-98d5-608c67c1aee5.png)

**Comment by DreamsOfImran** [comment]
Hi, can I work on this?

**Comment by shaansubbaiah** [comment]
@DreamsOfImran Just saw this, thanks for your interest in contributing to this repo! I had some time today and was finally able to fix this. You could try fixing issue #32

**Comment by DreamsOfImran** [comment]
@shaansubbaiah Can you assign that to me?

**Comment by shaansubbaiah** [comment]
I think @hafizmuhammadshoaib has already attempted a fix, let's wait for him.
